名称 = "serverless-qrcode-hub"
主 = "索引.js"
兼容日期 = "2025-03-10"

[[d1_数据库]]
绑定 = "数据库"
数据库名称 = "二维码中心"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
数据库ID = "d14f39de-6cd0-43a8-b275-f1f70b90c32c"

[触发器]
crons = ["0 2 */1 * *"]

[[开发环境数据库]]
绑定 = "数据库"
数据库名称 = "qrcode_hub_dev"
数据库ID = "efae31f5-7870-43c2-97d5-939f6f7afe7e"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[资产]
目录 = "./dist"
绑定 = “资产”
